CREATE TABLE mp_users (
	USER_ID NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(50) UNIQUE,
	DISPLAY_NAME_EN VARCHAR2(200),
	DISPLAY_NAME_AR VARCHAR2(200),
	USER_TYPE NUMBER,
	STATUS NUMBER,
	CREATE_DATE DATE,
	LAST_LOGIN_DATE DATE
);

CREATE TABLE mp_user_passwords (
	USER_PASS_ID NUMBER PRIMARY KEY,
	USER_ID NUMBER,
	USER_PASS VARCHAR(200),
	PASS_STATUS NUMBER,
	PASS_DATE DATE,
	CONSTRAINT USER_PASS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES mp_users(USER_ID)
);

CREATE TABLE mp_roles (
	ROLE_ID NUMBER PRIMARY KEY,
	ROLE_VAL VARCHAR2(50)
);

CREATE TABLE mp_user_roles (
	USER_ID NUMBER,
	ROLE_ID NUMBER,
	CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID),
	CONSTRAINT USER_ROLES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES mp_users(USER_ID),
	CONSTRAINT USER_ROLES_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES mp_roles(ROLE_ID)
);

-----------
INSERT INTO MP_ROLES VALUES (1, 'sys_admin');
INSERT INTO MP_ROLES VALUES (2, 'integ_team');
INSERT INTO MP_ROLES VALUES (3, 'app_support');

-----------------------------------------------------
----------------- Audit Payload Scripts -----------------
-----------------------------------------------------

CREATE TABLE "AUDIT_SERVICES" (
  	"SERVICE_ID" NUMBER PRIMARY KEY,
  	"SERVICE_NAME" VARCHAR(100)
);

CREATE TABLE "AUDIT_PAYLOADS" (
  	"AUDIT_PAYLOAD_ID" NUMBER PRIMARY KEY,
  	"AUDIT_PAYLOAD_TRX_ID" VARCHAR(200) NOT NULL,
  	"SERVICE_ID" NUMBER,
    "PAYLOAD_TYPE" NUMBER,-- REQUEST, RESPONSE & FAULT types
  	"CHANNEL_KEY" VARCHAR(100),
  	"AUDIT_PAYLOAD_DATE" DATE,
  	"PAYLOAD" CLOB
);

CREATE SEQUENCE AUDIT_PAYLOAD_ID_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999999999999999999999999
MINVALUE 1
NOCYCLE
CACHE 20;


INSERT INTO AUDIT_SERVICES (SERVICE_ID, SERVICE_NAME) VALUES (1, 'CustomerLookupService');
INSERT INTO AUDIT_SERVICES (SERVICE_ID, SERVICE_NAME) VALUES (2, 'BIPrunReportService');



